#!/bin/bash

#Checking constantly the state of disk and encrypted files on it

#path to mainfolder
path=/home/($USER)/*

#one week 
expirationToken=604800

#current date
currentDate=$date(+%s)


#Checking passphrase expiration for each encrypted package 
for FILE in "$path"; do
	if [ -f "$FILE.gpg" ]; then
		lastModifiedDate==$(stat -c %Y "$FILE")
		if [ ($currentDate - $lastModifiedDate) -gt $expirationToken ]; then
			read -p "Warning: $FILE uses a passphrase that exists more than 7 days. Would you like to change the passphrase? (y/n)" confirmation
			if [ $confirmation == "y" ]; then
				read -p "Put the passphrase of the file" pass
				sudo bash changePassphrase.sh $FILE $pass
			fi
