#!/bin/bash

if [ "$EUID" -ne 0 ]; then
    echo "Error: only root can run the script. Type sudo bash $0"
    exit 1
fi

#check linux distribution type
if [ -f /etc/os-release ]; then

	. /etc/os-release
	DISTRO=$ID_LIKE
	
	case $DISTRO in
		ubuntu|debian)
			pack="apt-get"
			;;
		fedora|rhel|centOS)
			pack="yum"
			;;
		suso)
			pack="zypper"
			;;
		*)
			echo "Unsupported linux distro. Check readme files for additionnal info"
			exit 1
			;;
	esac
else
	echo "Error: Cannot determine linux distribution"
	exit 1
fi

echo "Installing all needed dependencies..."
$pack install -y gpg

#moving files into bin folder & changing the permissions, then removing the initial folder
echo "Putting every script in order..."
chmod 111 "$(pwd)"/* && mv "$(pwd)"/* /usr/local/bin/ 
cd .. && rm -r "$OLDPWD"
rm -r /usr/local/bin/setup

echo "Done"
