#!/bin/bash

if [ "$EUID" -ne 0 ]; then
    echo "Error: only root can run the script. Type sudo bash $0"
    exit 1
fi

#check linux distribution type
if [ -f /etc/os-release ]; then

	. /etc/os-release
	DISTRO=$ID_LIKE
	
	case $DISTRO in
		ubuntu|debian)
			pack="apt-get"
			;;
		fedora|rhel|centOS)
			pack="yum"
			;;
		suso)
			pack="zypper"
			;;
		*)
			echo "Unsupported linux distro. Check readme files for additionnal info"
			exit 1
			;;
	esac
else
	echo "Error: Cannot determine linux distribution"
	exit 1
fi

echo "Installing all needed dependencies..."
$pack install -y gpg
$pack install -y cron

#moving files into bin folder & changing the permissions, then removing the initial folder
echo "Putting every script in order..."
chmod 111 "$(pwd)"/* && mv "$(pwd)"/* /usr/local/bin/


#creating a separate part of disk for logs
#disk=$(lsblk -nd -o NAME,TYPE | awk '$2 == "disk" {print $1; exit}')

usr=$(whoami)

cd .. && rm -r "$OLDPWD"
mkdir home/"$usr"/database

#Cron job to checker script
systemctl start cron
systemctl enable cron
(crontab -l | grep -Fxq "0 9 * * * sh /usr/local/bin/checker") || (crontab -l; echo "0 9 * * * sh /usr/local/bin/checker") | crontab -
bash /usr/local/bin/checker


echo "Done"
rm -r /usr/local/bin/setup

